src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.html

Review commentaar verwerkt

---

src/main/app/src/app/core/toolbar/toolbar.component.html

Accountnaam wordt niet getoond met kleiner scherm - fix

---

src/main/app/src/app/shared/material-form-builder/form-components/readonly/readonly.component.html
src/main/app/src/app/shared/material-form-builder/form/form/form.component.ts
src/main/app/src/app/shared/material-form-builder/material-form-builder.module.ts
src/main/app/src/app/shared/pipes/datum.pipe.ts
src/main/app/src/app/shared/pipes/pipes.module.ts
src/main/app/src/app/shared/shared.module.ts
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/main/java/net/atos/zac/app/taken/converter/RESTTaakConverter.java

Taak update en pipe fixes voor readonly

---

src/main/app/src/index.html
src/main/java/net/atos/zac/util/indexRewriteFilter.java
src/main/webapp/WEB-INF/web.xml

BUG: Not found bij refresh van de pagina 

---

src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java

Fix voor verkeerd getoonde totaal aantal open zaken

---

src/main/app/package-lock.json
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.html
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.less
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.less
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/taken/taken.module.ts
src/main/app/src/app/taken/taken.service.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/taken/TakenRESTService.java

Taken verdelen op werkvoorraad - Taak vrijgeven

---

src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

Fix - Zaken-werkvoorraad wijzigt niet na switchen van groep en zaaktype

---

src/main/app/src/app/notities/notities.component.html

Veld en knop disablen logica - Aanmaken notitie knop is altijd ingeschakeld

---

src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.html
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/shared/edit/edit.component.less
src/main/app/src/styles.less

Css aanpassingen voor de readonly edit componenten

---

src/main/app/src/app/core/toolbar/toolbar.component.html
src/main/app/src/app/core/toolbar/toolbar.component.less

#3
Profiel knop netjes in beeld houden

Profiel knop netjes in beeld houden

---

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts

Zaakafhandelparameters bewerken - Algemene gegevens 

---

src/main/java/net/atos/client/or/object/model/ObjectRecord.java
src/main/java/net/atos/client/or/shared/ObjectRegistratieClientService.java
src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/client/zgw/ztc/ZTCClientService.java
src/main/java/net/atos/zac/aanvraag/ProductAanvraag.java
src/main/java/net/atos/zac/aanvraag/ProductAanvraagService.java
src/main/java/net/atos/zac/util/ConfigurationService.java

Het aanmaken van de zaak en het koppelen van de ProductAanvraag en aanvraag PDF aan de zaak

Twede deel aanmaken zaak vanuit start formulier

---

src/main/java/net/atos/zac/event/EventingService.java

zaakafhandelcomponent-97 CodeQL Analysis installeren

---

src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.html
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.ts
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

Vrijgeven knopje + behandelaar fix voor de autocomplete

---

src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

Werkvoorraad zoeken fix

---

src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java

Zaak vrijgeven fix

---

src/main/resources/schemas/V3__signaleringen.sql

Flyway script review heeft al plaatsgevonden.

zaakafhandelcomponent-236 Signaleringen tabel

---

src/main/app/src/app/shared/paginator/paginator-translator.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-182 - Pagina nummers worden onjuist/niet getoond

---

src/main/app/src/app/shared/edit/edit.component.ts

zaakafhandelcomponent-265 - Edit mode toont originele tekst na Annuleren

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-273 - Ken toe aan mijzelf knop niet meer te zien na afronden

---

src/main/java/net/atos/zac/app/taken/TakenRESTService.java

zaakafhandelcomponent-246 - Inzicht in wie een taak heeft behandeld/afgerond

---

src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/taken/taken.service.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/java/net/atos/zac/app/taken/TakenRESTService.java

zaakafhandelcomponent-199 - Assign to me fix voor zaken werkoverzicht

zaakafhandelcomponent-199 - Assign to me fix voor zaken werkoverzicht

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-388 - Frontend -> tonen initiator zaak view

zaakafhandelcomponent-388 - Frontend -> tonen initiator zaak view

---

src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zaken.service.ts

zaakafhandelcomponent-224 - Fixes voor Behandelaar veld

---

src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-399 -> Missende vertaling voor beschrijving

zaakafhandelcomponent-399 -> Missende vertaling voor beschrijving

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-407 - Opslaan filtering etc werklijsten

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html

zaakafhandelcomponent-424 -> Improvements op persoonsgegevens aanvrager

zaakafhandelcomponent-424 -> Improvements op persoonsgegevens aanvrager

---

src/main/app/src/app/shared/material-form-builder/form-components/date/date.component.ts
src/main/app/src/app/shared/material-form-builder/model/form-component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-417 - Validatiemelding ontbreekt bij registratiedatum

zaakafhandelcomponent-417 - Validatiemelding ontbreekt bij registratiedatum

---

src/main/app/src/app/shared/dynamic-table/model/werklijstdata.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-408 - Inladen zoekopdracht

---

src/main/app/src/app/notities/notities.component.html
src/main/app/src/app/notities/notities.component.ts

zaakafhandelcomponent-272 - Annuleer knop bij notitie

zaakafhandelcomponent-272 - Annuleer knop bij notitie

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-409 - Knop voor wissen zoekopdracht

---

src/main/app/src/app/zaken/zaken-mijn/zaken-mijn-datasource.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts

zaakafhandelcomponent-473 - Zaaktype bij Mijn Zaken word niet default geselecteerd

---

src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.less
src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.ts
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.less
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.ts
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.less
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.ts
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.less
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.ts
src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.html
src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.less
src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.ts
src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field.ts
src/main/app/src/app/shared/shared.module.ts
src/main/app/src/app/zaken/model/zaak-edit-met-reden-gegevens.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zaken.service.ts
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/app/zaken/converter/RESTZaakConverter.java
src/main/java/net/atos/zac/app/zaken/model/RESTZaakEditMetRedenGegevens.java

zaakafhandelcomponent-287 - Deel 1 -> Einddatum niet tonen als hij leeg is  + aanpasbaar maken vertrouwelijkheidaanduiding

zaakafhandelcomponent-287 - Deel 1 -> Einddatum niet tonen als hij leeg is  + aanpasbaar maken vertrouwelijkheidaanduiding

---

src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.html
src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.ts
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.ts
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.html
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.ts
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.html
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.ts
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.ts
src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.html
src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.ts
src/main/app/src/app/shared/edit/edit.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete-form-field-builder.ts
src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete-validators.ts
src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.ts
src/main/app/src/app/shared/material-form-builder/form/form-field/form-field.component.ts
src/main/app/src/app/shared/material-form-builder/form/form/form.component.ts
src/main/app/src/app/shared/material-form-builder/material-form-builder.service.ts
src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field-builder.ts
src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field.ts
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.ts
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.html
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.ts
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.ts

FormBuilder verbeteringen doorvoeren

---

src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts

zaakafhandelcomponent-321 - Aanpassing van de getoonde kolommen

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

zaakafhandelcomponent-521 - Vervangen X icoontje (Wis zoekopdracht)

---

src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.html
src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.less
src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.ts

zaakafhandelcomponent-287 -> styling + responsive

zaakafhandelcomponent-287 -> styling + responsive

---

src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.ts
src/main/app/src/app/taken/taak-view/taak-view.component.ts

zaakafhandelcomponent-202 -> Toelichting bij taak gaf error bij opslaan

zaakafhandelcomponent-202 -> Toelichting bij taak gaf error bij opslaan

---

src/main/app/src/app/shared/edit/edit-vertrouwelijkheidaanduiding/edit-vertrouwelijkheidaanduiding.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-287 -> Vul gekozen waarde bij select

zaakafhandelcomponent-287 -> Vul gekozen waarde bij select

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-534 -Wissen zoekopdracht

---

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html

zaakafhandelcomponent-334 - Terugzetten zaakbeeindigFormGroup step

---

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html

zaakafhandelcomponent-334 - 'Volgende' knop toegevoegd

---

src/main/app/src/app/shared/dynamic-table/datasource/table-data-source.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-535 - Wissen zoekopdracht maakt nu ook tabel leeg

---

src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-533 - Wisselen van type toont/verbergt kolom

---

src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts

zaakafhandelcomponent-536 - Wissen zoekparameters Mijn Zaken

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-544 -> Redenvelden opschonen naar 1 reden veld

zaakafhandelcomponent-544 -> Redenvelden opschonen naar 1 reden veld

---

src/main/java/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.java
src/main/java/net/atos/zac/flowable/cmmn/event/CmmnEventObserver.java
src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterBeheerService.java
src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterService.java

zaakafhandelparameters refactoren

---

src/main/java/net/atos/zac/documenten/OntkoppeldeDocumentenService.java
src/main/java/net/atos/zac/documenten/model/OntkoppeldDocument.java
src/main/java/net/atos/zac/shared/model/ListParameters.java
src/main/java/net/atos/zac/shared/model/Paging.java
src/main/java/net/atos/zac/shared/model/SortDirection.java
src/main/java/net/atos/zac/shared/model/Sorting.java
src/main/resources/schemas/V6__ontkoppeld_document.sql

zaakafhandelcomponent-572 DocumentenService maken (crud voor verzamellijst)

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/java/net/atos/zac/app/taken/model/TaakSortering.java

zaakafhandelcomponent-565 - Sorteren bij taak werklijsten gefixt

---

src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-600 - Vertaling Body -> Bericht

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-595 - Snackbar voor initiator toevoegen/verwijderen

---

src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-601 - Snackbar bij versturen email

---

src/main/app/src/app/taken/taak-view/taak-view.component.ts

zaakafhandelcomponent-604 - Snackbar bij tussentijds opslaan

---

src/main/app/src/app/ontkoppelde-documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

zaakafhandelcomponent-633 DatePipe in Uitklap van lijsten

---

src/main/app/src/app/informatie-objecten/informatie-object-create/informatie-object-create.component.ts

zaakafhandelcomponent-610 BUG: Uitlijning bij document toevoegen

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-649 - Menu item Ontvangstbevestiging

---

src/main/app/src/app/shared/material-form-builder/model/form-component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-644 foutmeldingen kvk en vestigingsnummer in bedrijf toevoegen overlay fixen

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-629 - Menu header Initator verdwijnt niet

zaakafhandelcomponent-629 - Menu header Initator verdwijnt niet

---

src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/mail/model/mailobject.ts
src/main/java/net/atos/zac/app/mail/MailRESTService.java
src/main/java/net/atos/zac/app/mail/model/RESTMailObject.java
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-476 - mail document aanmaken optioneel

zaakafhandelcomponent-476 - mail document aanmaken optioneel

---

src/main/app/src/app/ontkoppelde-documenten/model/ontkoppeld-document.ts
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/converter/RESTOntkoppeldDocumentConverter.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/model/RESTOntkoppeldDocument.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/documenten/OntkoppeldeDocumentenService.java
src/main/java/net/atos/zac/documenten/model/OntkoppeldDocument.java
src/main/resources/schemas/V10__ontkoppelde_documenten_extra_velden.sql

Ontkoppelde documenten: Extra velden - Service en Entity #690

---

src/main/app/src/app/ontkoppelde-documenten/model/ontkoppeld-document.ts
src/main/app/src/app/ontkoppelde-documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/ontkoppelde-documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.less
src/main/app/src/app/ontkoppelde-documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/shared/dialog/dialog-data.ts
src/main/app/src/app/shared/dialog/dialog.component.html
src/main/app/src/app/shared/pipes/datum.pipe.ts
src/main/app/src/app/zaken/model/document-ontkoppel-gegevens.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zaken.service.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/zac/aanvraag/ProductAanvraagService.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/converter/RESTOntkoppeldDocumentConverter.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/model/RESTOntkoppeldDocument.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/app/zaken/model/RESTDocumentOntkoppelGegevens.java
src/main/java/net/atos/zac/documenten/OntkoppeldeDocumentenService.java
src/main/java/net/atos/zac/documenten/model/OntkoppeldDocument.java

zaakafhandelcomponent-691 Ontkoppelde documenten: Front-end

---

src/main/app/src/app/zaken/model/zaak-overzicht.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/java/net/atos/zac/app/zaken/model/RESTZaakOverzicht.java

zaakafhandelcomponent-687 BUG: Initiator header wordt getoond, echter niet ingeladen

---

src/main/app/src/app/formulieren/model/aanvullende-informatie.ts
src/main/app/src/app/plan-items/model/taak-stuur-gegevens.ts
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/planitems/model/RESTTaakStuurGegevens.java
src/main/java/net/atos/zac/flowable/FlowableService.java

zaakafhandelcomponent-476 - Aanvullende info taak met mailfunctionaliteit - Mail template

zaakafhandelcomponent-476 - Aanvullende info taak met mailfunctionaliteit - Mail template

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/app/src/styles.less
src/main/java/net/atos/zac/aanvraag/ProductAanvraagService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieobject.java

zaakafhandelcomponent-603 Tonen van startformulier bij zaakgegevens pagina

---

src/main/java/net/atos/zac/zaaksturing/model/UserEventListenerParameters.java
src/main/resources/schemas/V12__usereventlistener_parameters.sql

zaakafhandelcomponent-472 - script + entiteit User event listener toelichting

zaakafhandelcomponent-472 - script + entiteit User event listener toelichting

---

src/main/java/net/atos/zac/zaaksturing/model/UserEventListenerParameters.java
src/main/java/net/atos/zac/zaaksturing/model/ZaakafhandelParameters.java
src/main/resources/schemas/V12__usereventlistener_parameters.sql

zaakafhandelcomponent-472 - Script + entiteit User event listener

zaakafhandelcomponent-472 - Script + entiteit User event listener

---

src/main/java/net/atos/zac/app/mail/MailRESTService.java
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-726 - Onnodige afhankelijk op Mailjet

zaakafhandelcomponent-726 - Onnodige afhankelijk op Mailjet

---

src/main/app/src/app/shared/dynamic-table/pipes/tooltip-list.pipe.ts

zaakafhandelcomponent-745 - Bug in list pipe

zaakafhandelcomponent-745 - Bug in list pipe

---

src/main/app/src/app/shared/pipes/location.pipe.ts
src/main/app/src/app/shared/pipes/pipes.module.ts
src/main/app/src/app/shared/read-more/read-more.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zoek/locatie-zoek/locatie-zoek.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/client/zgw/zrc/model/Geometry.java
src/main/java/net/atos/client/zgw/zrc/model/GeometryCollection.java
src/main/java/net/atos/client/zgw/zrc/model/Point.java
src/main/java/net/atos/client/zgw/zrc/model/Polygon.java
src/main/java/net/atos/zac/app/audit/converter/zaken/AuditZaakWijzigingConverter.java
src/main/java/net/atos/zac/app/zaken/converter/RESTZaakConverter.java

Locatiedata terug vinden in de historie

---

src/main/app/src/app/admin/model/human-task-parameter.ts
src/main/app/src/app/admin/model/zaakafhandel-parameters.ts
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts
src/main/app/src/app/plan-items/plan-items.service.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/admin/converter/RESTZaakafhandelParametersConverter.java
src/main/java/net/atos/zac/app/admin/model/RESTHumanTaskParameters.java
src/main/java/net/atos/zac/app/admin/model/RESTZaakafhandelParameters.java
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/planitems/converter/RESTPlanItemConverter.java
src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterBeheerService.java
src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterService.java
src/main/java/net/atos/zac/zaaksturing/model/HumanTaskParameters.java
src/main/java/net/atos/zac/zaaksturing/model/ZaakafhandelParameters.java
src/main/resources/schemas/V13__hernoemen_planitem_naar_humantask.sql

zaakafhandelcomponent-745 - Hernoemen PlanItem -> HumanTask

zaakafhandelcomponent-745 - Hernoemen PlanItem -> HumanTask

---

src/main/java/net/atos/client/zgw/zrc/model/Geometry.java
src/main/java/net/atos/client/zgw/zrc/model/GeometryCollection.java
src/main/java/net/atos/client/zgw/zrc/model/Point.java
src/main/java/net/atos/client/zgw/zrc/model/Point2D.java
src/main/java/net/atos/client/zgw/zrc/model/Polygon.java

Locatiedata terug vinden in de historie #733

Locatiedata terug vinden in de historie #733

---

src/main/app/src/app/informatie-objecten/informatie-object-create/informatie-object-create.component.ts
src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/mail/ontvangstbevestiging/ontvangstbevestiging.component.ts
src/main/app/src/app/plan-items/human-task-do/human-task-do.component.ts

zaakafhandelcomponent-835 BUG: Titel in toolbar veranderd door de side-nav

---

src/main/app/src/app/informatie-objecten/informatie-object-create/informatie-object-create.component.ts
src/main/app/src/app/shared/material-form-builder/form/form/form.component.ts

zaakafhandelcomponent-797 BUG: Annuleer knop op bij document toevoegen 

---

src/main/app/src/app/shared/document-viewer/document-viewer.component.ts
src/main/app/src/styles.less

3 scrolbalken zichtbaar #793

---

src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-779 - Kolom omschrijving in zaakwerklijsten

zaakafhandelcomponent-779 - Kolom omschrijving in zaakwerklijsten

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-756 - Limiet bij redenveld

zaakafhandelcomponent-756 - Limiet bij redenveld

---

src/main/app/src/app/zaken/zoek/locatie-zoek/locatie-zoek.component.ts

BUG: Verwijderen van locatie gebeurt niet #810

BUG: Verwijderen van locatie gebeurt niet #810

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html

zaakafhandelcomponent-807 - Consistent datumformaat bij Historie

---

src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.ts

zaakafhandelcomponent-806 - Historie: toelichting van vrijgeven zaak fix

---

src/main/app/src/app/formulieren/model/aanvullende-informatie.ts

zaakafhandelcomponent-827 BUG:  Opslaan bij aanvullende info werkt niet 

---

src/main/app/src/app/shared/edit/edit-select/edit-select.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

zaakafhandelcomponent-858 - Opruimen van onnodige translate pipes

---

src/main/app/src/app/shared/historie/model/taak-historie-regel.ts
src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/taken/taken.service.ts

taakhistorie Deel 2 #789

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

#757
Vraagteken icon naar info icon bij zaak status en resultaat

zaakafhandelcomponent-757 - Icon verandering

---

src/main/resources/schemas/V14__planitem_parameters_doorlooptijd_drop_not_null.sql

Streefdatum bij een taak niet verplicht #853

Streefdatum bij een taak niet verplicht #853

---

src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

zaakafhandelcomponent-840 - Placeholder bij Zaken werklijsten

---

src/main/app/src/app/app.component.html
src/main/app/src/app/zoeken/model/zoek-parameters.ts
src/main/app/src/app/zoeken/zoek-object/document-zoek-object/document-zoek-object.component.html
src/main/app/src/app/zoeken/zoek-object/document-zoek-object/document-zoek-object.component.ts
src/main/app/src/app/zoeken/zoek-object/zaak-zoek-object/zaak-zoek-object.component.html
src/main/app/src/app/zoeken/zoek-object/zaak-zoek-object/zaak-zoek-object.component.ts
src/main/app/src/app/zoeken/zoek-object/zaak-zoek-object/zoek-zaak-object.component.less
src/main/app/src/app/zoeken/zoek-object/zoek-object/zoek-object-component.ts
src/main/app/src/app/zoeken/zoek/zoek.component.html
src/main/app/src/app/zoeken/zoek/zoek.component.less
src/main/app/src/app/zoeken/zoek/zoek.component.ts
src/main/app/src/app/zoeken/zoeken.module.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/app/src/styles.less
src/main/java/net/atos/zac/app/zoeken/ZoekenRESTService.java
src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekParametersConverter.java
src/main/java/net/atos/zac/app/zoeken/model/RESTZoekParameters.java
src/main/java/net/atos/zac/zoeken/ZoekenService.java
src/main/java/net/atos/zac/zoeken/model/ZoekParameters.java
src/main/resources/solr-schema/schema.xml

zaakafhandelcomponent-816 Zoek zaken - Implementatie front end

---

src/main/app/src/styles.less

zaakafhandelcomponent-893 - Sidenav stopt halverwege

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts

zaakafhandelcomponent-849 - Document refreshen na toevoegen nieuwe versie

zaakafhandelcomponent-849 - Document refreshen na toevoegen nieuwe versie

---

src/main/app/src/app/shared/static-text/static-text.component.ts

zaakafhandelcomponent-976 - Toelichting icoon word niet meteen getoond 

---

src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-898 - Gebruiksrechten verwijderen bij aanmaken document

zaakafhandelcomponent-898 - Gebruiksrechten verwijderen bij aanmaken document

---

src/main/app/src/app/fout-afhandeling/fout-afhandeling.component.html

zaakafhandelcomponent-977 - e-Suite uit naam foutafhandelpagina halen

zaakafhandelcomponent-977 - e-Suite uit naam foutafhandelpagina halen

---

src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java

zaakafhandelcomponent-973 - Formaat update bij nieuwe versie documentupload

zaakafhandelcomponent-973 - Formaat update bij nieuwe versie documentupload

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/app/src/app/shared/pipes/datum.pipe.ts

zaakafhandelcomponent-975 - Registratiedatum in history leesbaar maken

zaakafhandelcomponent-975 - Registratiedatum in history leesbaar maken

---

src/main/app/src/app/app.globals.ts
src/main/java/net/atos/zac/app/zoeken/ZoekenRESTService.java
src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekParametersConverter.java
src/main/java/net/atos/zac/zoeken/ZoekenService.java
src/main/java/net/atos/zac/zoeken/model/FilterVeld.java
src/main/java/net/atos/zac/zoeken/model/SorteerVeld.java
src/main/java/net/atos/zac/zoeken/model/Sortering.java
src/main/java/net/atos/zac/zoeken/model/ZoekParameters.java
src/main/java/net/atos/zac/zoeken/model/ZoekResultaat.java
src/main/java/net/atos/zac/zoeken/model/ZoekVeld.java
src/main/resources/solr-schema/schema.xml

zaakafhandelcomponent-1008 ZoekService uitbreiden voor werklijst functionaliteit

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html

zaakafhandelcomponent-897 - Vertaling status bij document

zaakafhandelcomponent-897 - Vertaling status bij document

---

src/main/app/src/app/informatie-objecten/informatie-object-create/informatie-object-create.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieObjectVersieGegevens.java
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-802 - Ontvangst en verzenddatum

zaakafhandelcomponent-802 - Ontvangst en verzenddatum

---

src/main/app/src/app/shared/dynamic-table/datasource/zoeken-table-data-source.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvorraad-datasource.ts
src/main/app/src/app/zoeken/model/zoek-parameters.ts
src/main/app/src/app/zoeken/zoek/zoek.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekParametersConverter.java
src/main/java/net/atos/zac/app/zoeken/model/RESTZoekParameters.java
src/main/java/net/atos/zac/zoeken/IndexeerService.java

zaakafhandelcomponent-1032 opslaan zoekopdracht

---

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts

zaakafhandelcomponent-1069 - Document leegmaken alleen bij klikken op annuleer knop

zaakafhandelcomponent-1069 - Document leegmaken alleen bij klikken op annuleer knop

---

src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-1090 - Missende vertaling

zaakafhandelcomponent-1090 - Missende vertaling

---

src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-1087 - Fout bij zaakafronden bij aanwezigheid document

zaakafhandelcomponent-1087 - Fout bij zaakafronden bij aanwezigheid document

---

src/main/app/src/app/zaken/model/indicatie.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.less

zaakafhandelcomponent-888 Tonen van indicaties

---

src/main/app/src/app/core/actionbar/action-bar.component.html
src/main/app/src/app/core/actionbar/action-bar.component.ts
src/main/app/src/app/core/service/util.service.ts
src/main/app/src/app/klanten/bedrijfsgegevens/bedrijfsgegevens.component.html
src/main/app/src/app/klanten/bedrijfsgegevens/bedrijfsgegevens.component.ts
src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.html
src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.ts
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.html
src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.ts
src/main/app/src/app/shared/edit/edit-datum/edit-datum.component.html
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.html
src/main/app/src/app/shared/edit/edit-select/edit-select.component.html
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.html
src/main/app/src/app/shared/edit/edit.component.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-1091 - Zaakacties niet tonen wanneer de zaak is afgesloten

zaakafhandelcomponent-1091 - Zaakacties niet tonen wanneer de zaak is afgesloten

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-1091

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts
src/main/app/src/app/informatie-objecten/model/file-format.ts
src/main/app/src/app/informatie-objecten/model/file-icon.ts

zaakafhandelcomponent-1133 - .ppt geeft onjuist icoon weer

zaakafhandelcomponent-1133 - .ppt geeft onjuist icoon weer

---

src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

uitklap gedeelte mijn en werkvoorraard

zaakafhandelcomponent-1129 BUG: werkvoorraad filter incorrect 

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts

zaakafhandelcomponent-1131 - Download juiste versie document

zaakafhandelcomponent-1131 - Download juiste versie document

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts
src/main/app/src/app/informatie-objecten/model/file-format.ts

zaakafhandelcomponent-1139 - Webdav alleen aanbieden bij office bestanden

zaakafhandelcomponent-1139 - Webdav alleen aanbieden bij office bestanden 

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts

zaakafhandelcomponent-1107 - Document mutaties niet toestaan als de zaak is gesloten

zaakafhandelcomponent-1107 - Document mutaties niet toestaan als de zaak is gesloten

---

src/main/resources/solr-schema/schema.xml

zaakafhandelcomponent-1172 Taken zoeken

---

src/main/app/src/app/zaken/model/zaak-rechten.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/zaken/converter/RESTZaakRechtenConverter.java
src/main/java/net/atos/zac/app/zaken/model/RESTZaakRechten.java

zaakafhandelcomponent-895 - Verwijderen van zaken niet toestaan bij hoofdzaak met open deelzaken

zaakafhandelcomponent-895 - Verwijderen van zaken niet toestaan bij hoofdzaak met open deelzaken

---

src/main/app/src/app/app.component.ts
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-verplaats.service.ts
src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-1169 - Document verplaatsen logica naar aparte service

zaakafhandelcomponent-1169 - Document verplaatsen logica naar aparte service

---

src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-895 - Extra snackbar weghalen

zaakafhandelcomponent-895 - Extra snackbar weghalen

---

src/main/app/src/app/documenten/documenten.module.ts
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.less
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/inbox-documenten.service.ts
src/main/app/src/app/documenten/model/inbox-document-list-parameters.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.less
src/main/app/src/app/zoeken/tekst-filter/tekst-filter.component.ts
src/main/java/net/atos/zac/app/inboxdocumenten/InboxDocumentenRESTService.java
src/main/java/net/atos/zac/app/inboxdocumenten/converter/RESTInboxDocumentListParametersConverter.java
src/main/java/net/atos/zac/app/inboxdocumenten/model/RESTInboxDocumentListParameters.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/converter/RESTOntkoppeldDocumentListParametersConverter.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/model/RESTOntkoppeldDocumentListParameters.java
src/main/java/net/atos/zac/app/shared/RESTListParametersConverter.java
src/main/java/net/atos/zac/documenten/InboxDocumentenService.java
src/main/java/net/atos/zac/documenten/OntkoppeldeDocumentenService.java
src/main/java/net/atos/zac/documenten/model/InboxDocument.java
src/main/java/net/atos/zac/documenten/model/InboxDocumentListParameters.java
src/main/java/net/atos/zac/documenten/model/OntkoppeldDocumentListParameters.java

zaakafhandelcomponent-1115 Filteren en sortering op Inbox documenten

---

src/main/java/net/atos/zac/util/IndexerenRESTService.java
src/main/java/net/atos/zac/zoeken/IndexeerService.java
src/main/java/net/atos/zac/zoeken/model/index/ZoekObjectType.java

zaakafhandelcomponent-1223 Indexeer service en cron aanpassen

---

src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.html
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-895 - Disable koppel knop bij geen koppeling mogelijk

zaakafhandelcomponent-895 - Disable koppel knop bij geen koppeling mogelijk

---

src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld-datasource.ts

zaakafhandelcomponent-1226 BUG: Filters op afgehandelde zaken 

---

src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts
src/main/app/src/app/shared/validators/customValidators.ts

zaakafhandelcomponent-813 - Handelsnaam regex

zaakafhandelcomponent-813 - Handelsnaam regex

---

src/main/app/src/app/documenten/documenten.module.ts
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/gebruikersvoorkeuren/gebruikersvoorkeuren.module.ts
src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekopdracht.component.html
src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekopdracht.component.less
src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekopdracht.component.ts
src/main/app/src/app/shared/dynamic-table/datasource/zoeken-table-data-source.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn-datasource.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad-datasource.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/taken/taken.module.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld-datasource.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn-datasource.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad-datasource.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken.module.ts

zoekopdracht logica verplaatst naar component

zaakafhandelcomponent-1240 werkvoorraad filters bewaren ook na uitloggen. 

---

src/main/java/net/atos/zac/flowable/TaskService.java
src/main/java/net/atos/zac/util/JsonbUtil.java

zaakafhandelcomponent-1310 - 500 bij toelichting taak

zaakafhandelcomponent-1310 - 500 bij toelichting taak

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-1302 - Openen dialog sluit niet de sidenav

zaakafhandelcomponent-1302 - Openen dialog sluit niet de sidenav

---

src/main/app/src/app/zaken/zaak-ontkoppelen/zaak-ontkoppelen-dialog.component.ts

zaakafhandelcomponent-1317 - Reden veld verplicht bij ontkoppelen zaak

zaakafhandelcomponent-1317 - Reden veld verplicht bij ontkoppelen zaak

---

src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
src/main/app/src/app/informatie-objecten/model/gekoppelde.zaak.enkelvoudig.informatieobject.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.less
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTGekoppeldeZaakEnkelvoudigInformatieObject.java

zaakafhandelcomponent-1234 - Tonen van documenten van gekoppelde zaken

zaakafhandelcomponent-1234 - Tonen van documenten van gekoppelde zaken

---

src/main/app/src/app/formulieren/model/advies.ts
src/main/app/src/app/formulieren/model/goedkeuren.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.ts
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java

zaakafhandelcomponent-1382 - 500 error bij advies intern

zaakafhandelcomponent-1382 - 500 error bij advies intern

---

src/main/app/src/app/admin/zaakafhandel-parameters.service.ts
src/main/app/src/app/bag/bag.service.ts
src/main/app/src/app/configuratie/configuratie.service.ts
src/main/app/src/app/documenten/inbox-documenten.service.ts
src/main/app/src/app/documenten/ontkoppelde-documenten.service.ts
src/main/app/src/app/fout-afhandeling/dialog/fout-dialog.component.html
src/main/app/src/app/fout-afhandeling/dialog/fout-dialog.component.ts
src/main/app/src/app/fout-afhandeling/fout-afhandeling.module.ts
src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
src/main/app/src/app/gebruikersvoorkeuren/gebruikersvoorkeuren.service.ts
src/main/app/src/app/identity/identity.service.ts
src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
src/main/app/src/app/klanten/klanten.service.ts
src/main/app/src/app/mail/mail.service.ts
src/main/app/src/app/notities/notities.service.ts
src/main/app/src/app/plan-items/plan-items.service.ts
src/main/app/src/app/policy/policy.service.ts
src/main/app/src/app/shared/location/location.service.ts
src/main/app/src/app/signaleringen.service.ts
src/main/app/src/app/signaleringen/signaleringen-settings.service.ts
src/main/app/src/app/taken/taken.service.ts
src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.ts
src/main/app/src/app/zaken/zaken.service.ts
src/main/app/src/app/zoeken/zoeken.service.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/shared/exception/FoutMeldingExceptionMapper.java
src/main/java/net/atos/zac/shared/exception/ValidatieFoutExceptionMapper.java

zaakafhandelcomponent-1258 - Foutmeldingen uit open zaak tonen aan gebruiker

zaakafhandelcomponent-1258 - Foutmeldingen uit open zaak tonen aan gebruiker

---

src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/policy/PolicyService.java

zaakafhandelcomponent-1396 - Controle openstaande deelzaken bij zaak afsluiten, afbreken en afhandelen

zaakafhandelcomponent-1396 - Controle openstaande deelzaken bij zaak afsluiten, afbreken en afhandelen

---

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

zaakafhandelcomponent-1411 - Verbetering op foutafhandeling dialog

zaakafhandelcomponent-1411 - Verbetering op foutafhandeling dialog

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.less
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-1439 - Improvements downloaden zip

zaakafhandelcomponent-1439 - Improvements downloaden zip

---

src/main/app/src/app/formulieren/model/aanvullende-informatie.ts
src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/mail/model/mailobject.ts
src/main/app/src/app/mail/ontvangstbevestiging/ontvangstbevestiging.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.ts
src/main/java/net/atos/zac/app/mail/MailRESTService.java
src/main/java/net/atos/zac/app/mail/model/RESTMailObject.java
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/java/net/atos/zac/mail/MailService.java
src/main/java/net/atos/zac/mail/model/Attachment.java
src/main/java/net/atos/zac/mail/model/EMail.java
src/main/java/net/atos/zac/signalering/SignaleringenService.java

zaakafhandelcomponent-1180 - Bijlage bij mail

zaakafhandelcomponent-1180 - Bijlage bij mail

---

src/main/app/src/app/core/websocket/websocket.service.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-1421 - Taken worden niet gelijk getoond

zaakafhandelcomponent-1421 - Taken worden niet gelijk getoond

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-305 - Select all knop uitzetten na downloaden

zaakafhandelcomponent-305 - Select all knop uitzetten na downloaden

---

src/main/java/net/atos/client/zgw/drc/DRCClientService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java

zaakafhandelcomponent-1368 - Functie omzetten UUID naar URL

zaakafhandelcomponent-1368 - Functie omzetten UUID naar URL

---

src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/zac/app/bag/BAGRESTService.java
src/main/java/net/atos/zac/app/inboxdocumenten/InboxDocumentenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

zaakafhandelcomponent-1413 - Functie omzetten UUID naar URL

zaakafhandelcomponent-1413 - Functie omzetten UUID naar URL

---

src/main/app/src/app/klanten/zoek/klanten/klant-zoek.component.ts

Zie ook deze comment https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1401#issuecomment-1219550824

zaakafhandelcomponent-1401 Gebruikte karakters toelichting betrokkene toevoegen

---

src/main/java/net/atos/zac/app/zaken/converter/RESTZaakConverter.java

Vervolg-PR op https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/1475

zaakafhandelcomponent-1422 Verwijder achtergebleven reference naar verwijderde property

---

src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/shared/dynamic-table/datasource/zoeken-data-source.ts

zaakafhandelcomponent-1484 laden van werklijsten fixen

---

src/main/app/src/app/shared/dynamic-table/datasource/zoeken-data-source.ts

zaakafhandelcomponent-1338 BUG: Filters worden gereset met wijziging kolommen

---

src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/zac/app/bag/BAGRESTService.java
src/main/java/net/atos/zac/app/inboxdocumenten/InboxDocumentenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

zaakafhandelcomponent-1413 - Revert UUID -> Url aanpassing

zaakafhandelcomponent-1413 - Revert UUID -> Url aanpassing

---

src/main/app/src/app/informatie-objecten/informatie-object-indicaties/informatie-object-indicaties.component.html

zaakafhandelcomponent-1499 BUG: Datumformat na hover indicatie niet juist

---

src/main/app/src/app/core/service/util.service.ts

zaakafhandelcomponent-443 - Blow download met filenaam mogelijk maken

zaakafhandelcomponent-443 - Blow download met filenaam mogelijk maken

---

src/main/java/net/atos/client/zgw/brc/BRCClient.java
src/main/java/net/atos/client/zgw/brc/BRCClientService.java
src/main/java/net/atos/client/zgw/brc/model/Besluit.java
src/main/java/net/atos/client/zgw/brc/model/BesluitenListParameters.java
src/main/java/net/atos/client/zgw/brc/model/Vervalreden.java
src/main/java/net/atos/client/zgw/shared/cache/Caching.java
src/main/java/net/atos/client/zgw/shared/cache/event/CacheEventObserver.java
src/main/java/net/atos/client/zgw/ztc/ZTCClient.java
src/main/java/net/atos/client/zgw/ztc/ZTCClientService.java
src/main/java/net/atos/client/zgw/ztc/model/Besluittype.java
src/main/java/net/atos/client/zgw/ztc/model/BesluittypeListParameters.java
src/main/java/net/atos/zac/app/util/UtilRESTService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/app/zaken/converter/RESTBesluitConverter.java
src/main/java/net/atos/zac/app/zaken/converter/RESTBesluittypeConverter.java
src/main/java/net/atos/zac/app/zaken/converter/RESTZaakActiesConverter.java
src/main/java/net/atos/zac/app/zaken/converter/RESTZaakConverter.java
src/main/java/net/atos/zac/app/zaken/model/RESTBesluit.java
src/main/java/net/atos/zac/app/zaken/model/RESTBesluitToevoegenGegevens.java
src/main/java/net/atos/zac/app/zaken/model/RESTBesluittype.java
src/main/java/net/atos/zac/app/zaken/model/RESTZaak.java
src/main/java/net/atos/zac/app/zaken/model/RESTZaakActies.java
src/main/java/net/atos/zac/policy/PolicyService.java
src/main/java/net/atos/zac/policy/input/ZaakData.java
src/main/java/net/atos/zac/policy/output/ZaakActies.java
src/main/resources/policies/zaak-acties.rego

zaakafhandelcomponent-1526 Besluit model en backend-service

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/java/net/atos/zac/app/audit/converter/documenten/AuditEnkelvoudigInformatieobjectConverter.java

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1528.
Implementatie afgekeken van `zaak-view.component`.

zaakafhandelcomponent-1528 Voeg datum-pipe toe voor de ondertekening

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts
src/main/java/net/atos/zac/aanvraag/ProductAanvraagService.java
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/main/java/net/atos/zac/app/zoeken/model/RESTTaakZoekObject.java
src/main/java/net/atos/zac/flowable/cmmn/event/CmmnEventObserver.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/java/net/atos/zac/zoeken/IndexeerService.java
src/main/java/net/atos/zac/zoeken/converter/TaakZoekObjectConverter.java
src/main/java/net/atos/zac/zoeken/model/TaakZoekObject.java
src/main/java/net/atos/zac/zoeken/model/ZaakZoekObject.java

zaakafhandelcomponent-1504 US: De zaakomschrijving ook tonen in de werklijst van taken 

---

src/main/java/net/atos/client/zgw/ztc/model/Informatieobjecttype.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjecttypeConverter.java

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1543

zaakafhandelcomponent-1543 Verberg ongeldige informatieobjecttypes

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1527

zaakafhandelcomponent-1527 verberg `-geen-` opties in zaak-view

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1549

zaakafhandelcomponent-1549 Wijzig icoontje voor ondertekenen informatieobject

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zoeken/model/taken/taak-zoek-object.ts
src/main/app/src/app/zoeken/tekst-filter/tekst-filter.component.less
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/zoeken/converter/RESTTaakZoekObjectConverter.java
src/main/java/net/atos/zac/zoeken/converter/TaakZoekObjectConverter.java

zaakafhandelcomponent-1504 US: De zaakomschrijving ook tonen in de werklijst van taken

---

src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
src/main/app/src/app/informatie-objecten/model/enkelvoudig-informatie-object-zoek-parameters.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTInformatieObjectZoekParameters.java

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1545

zaakafhandelcomponent-1545 Ophalen gekoppelde documenten met zoekparameter

---

src/main/resources/schemas/V28__zaakafhandelparameters_voeg_productaanvraagtype_toe.sql

Zaakafhandelparameters productaanvraagtype flyway

Zaakafhandelparameters productaanvraagtype flyway

---

src/main/app/src/app/shared/edit/edit-autocomplete/edit-autocomplete.component.ts
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-behandelaar/edit-behandelaar.component.ts
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.html
src/main/app/src/app/shared/edit/edit-groep/edit-groep.component.ts
src/main/app/src/app/shared/edit/edit-input/edit-input.component.ts
src/main/app/src/app/shared/edit/edit-select/edit-select.component.ts
src/main/app/src/app/shared/edit/edit-tekst/edit-tekst.component.ts
src/main/app/src/app/shared/edit/edit.component.ts

BUG: Vrijgeven behandelaar is verdwenen#1601

BUG: Vrijgeven behandelaar is verdwenen#1601

---

src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java

zaakafhandelcomponent-1600 - Dubbele : in history reden

zaakafhandelcomponent-1600 - Dubbele : in history reden

---

src/main/app/src/app/shared/material-form-builder/form/form-field/form-field.component.ts
src/main/app/src/app/shared/material-form-builder/form/form/form.component.ts
src/main/app/src/app/shared/material-form-builder/model/abstract-form-field.ts

zaakafhandelcomponent-1611 - Taken kunnen niet gestart worden

zaakafhandelcomponent-1611 - Taken kunnen niet gestart worden

---

src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.html
src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1596.

zaakafhandelcomponent-1596 Zaak-afhandelen-dialog form fields wel of niet tonen

---

src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.html

zaakafhandelcomponent-1591 - Documenttype wordt niet getoond in de verkorte weergave

zaakafhandelcomponent-1591 - Documenttype wordt niet getoond in de verkorte weergave

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1619.

zaakafhandelcomponent-1619 Ontvanger field in- en uitschakelen

---

src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.ts

zaakafhandelcomponent-1598 - BUG: Zaak afhandelen is mogelijk zonder gekozen resultaat

zaakafhandelcomponent-1598 - BUG: Zaak afhandelen is mogelijk zonder gekozen resultaat

---

src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.ts
src/main/app/src/app/zaken/besluit-edit/besluit-edit.component.ts
src/main/app/src/app/zaken/besluit-view/besluit-view.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zaken.service.ts
src/main/java/net/atos/client/zgw/brc/BRCClient.java
src/main/java/net/atos/client/zgw/brc/BRCClientService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

wijzigen documenten en resultaat

zaakafhandelcomponent-1570 Wijzigen besluit - documenten en resultaat

---

src/main/app/src/app/shared/navigation/back-button.directive.spec.ts
src/main/app/src/app/shared/storage/session-storage.util.spec.ts
src/main/java/net/atos/client/util/LoggingFilter.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/java/net/atos/zac/util/OpenZaakPaginationUtil.java

zaakafhandelcomponent-1468 - Vervangen placeholders/todo's ESUITEDEV nummers

zaakafhandelcomponent-1468 - Vervangen placeholders/todo's ESUITEDEV nummers

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1645.
Ook stukje refactor vanwege deprecated forkJoin-implementatie.

zaakafhandelcomponent-1645 Zaak afbreken tonen obv zaakafhandelparameters

---

src/main/app/src/app/zaken/besluit-view/besluit-view.component.ts
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

zaakafhandelcomponent-1685 Vastelggen besluit geeft PolicyException

---

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

Fixes https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1695.

zaakafhandelcomponent-1695 Collectie mutable voor gekoppelde zaakdocumenten

---

src/main/app/src/app/admin/parameters/parameters.component.html
src/main/app/src/app/admin/referentie-tabellen/referentie-tabellen.component.html
src/main/app/src/app/dashboard/informatieobjecten-card/informatieobjecten-card.component.html
src/main/app/src/app/dashboard/taken-card/taken-card.component.html
src/main/app/src/app/dashboard/zaak-waarschuwingen-card/zaak-waarschuwingen-card.component.html
src/main/app/src/app/dashboard/zaken-card/zaken-card.component.html
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-verkort/zaak-verkort.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html

zaakafhandelcomponent-1640 - Mogelijkheid tot openen in nieuwe tab of nieuw scherm

zaakafhandelcomponent-1640 - Mogelijkheid tot openen in nieuwe tab of nieuw scherm

---

src/main/java/net/atos/client/zgw/ztc/model/Zaaktype.java

zaakafhandelcomponent-1719 - 500 error bij starten zaak

zaakafhandelcomponent-1719 - 500 error bij starten zaak

---

src/main/app/src/app/policy/model/document-rechten.ts
src/main/java/net/atos/zac/app/policy/converter/RESTRechtenConverter.java
src/main/java/net/atos/zac/app/policy/model/RESTDocumentRechten.java

zaakafhandelcomponent-1717 - Document iconen niet zichtbaar

zaakafhandelcomponent-1717 - Document iconen niet zichtbaar

---

src/main/resources/schemas/V30__toevoegen_formulierdefinitie.sql

zaakafhandelcomponent-1743 Per taak kunnen kiezen welk formulier je wilt

---

src/main/app/src/app/admin/model/human-task-parameter.ts
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.less
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts
src/main/app/src/app/plan-items/model/plan-item.ts
src/main/java/net/atos/zac/app/admin/converter/RESTHumanTaskParametersConverter.java
src/main/java/net/atos/zac/app/admin/model/RESTHumanTaskParameters.java
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/planitems/converter/RESTPlanItemConverter.java
src/main/java/net/atos/zac/app/planitems/model/RESTPlanItem.java
src/main/java/net/atos/zac/zaaksturing/model/HumanTaskParameters.java

zaakafhandelcomponent-1744 Generieke functie om taken aan of uit te zetten

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts

BUG: Aanmaken zaak niet meer mogelijk; Aanmaken knop blijft disabled #1757

BUG: Aanmaken zaak niet meer mogelijk; Aanmaken knop blijft disabled #1757

---

src/main/java/net/atos/client/zgw/drc/model/AbstractEnkelvoudigInformatieobject.java

zaakafhandelcomponent-1731 - Ondertekenen van documenten geeft foutpagina

zaakafhandelcomponent-1731 - Ondertekenen van documenten geeft foutpagina

---

src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts

zaakafhandelcomponent-1729 - Inboxdocument werklijst geeft foutpagina bij sorteren

zaakafhandelcomponent-1729 - Inboxdocument werklijst geeft foutpagina bij sorteren

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts
src/main/app/src/app/shared/document-viewer/document-viewer.component.ts

zaakafhandelcomponent-1590 - Verwijderen document geeft foutpagina

zaakafhandelcomponent-1590 - Verwijderen document geeft foutpagina

---

src/main/app/src/app/shared/material-form-builder/form-components/select-medewerker/medewerker-groep.component.html
src/main/app/src/app/shared/material-form-builder/form-components/select-medewerker/medewerker-groep.component.ts

BUG: Wordt geen foutmelding getoond wanneer Groep niet gevuld is #1784

BUG: Wordt geen foutmelding getoond wanneer Groep niet gevuld is #1784

---

src/main/java/net/atos/zac/mailtemplates/MailTemplateService.java
src/main/java/net/atos/zac/mailtemplates/model/MailTemplate.java
src/main/java/net/atos/zac/mailtemplates/model/MailTemplateEnum.java
src/main/java/net/atos/zac/mailtemplates/model/MailTemplateVariabelen.java
src/main/resources/schemas/V33__mail_template.sql

zaakafhandelcomponent-1800 - Script, entity + service mailtemplates

zaakafhandelcomponent-1800 - Script, entity + service mailtemplates

---

src/main/resources/schemas/V33__mail_template.sql

zaakafhandelcomponent-1800 - komma in script

zaakafhandelcomponent-1800 - komma in script

---

src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

zaakafhandelcomponent-1732 Besluit ook kunnen aanmaken voor heropende zaken

---

src/main/java/net/atos/zac/identity/IdentityService.java

zaakafhandelcomponent-1583 Sorteer medewerkers op volledige naam

---

src/main/java/net/atos/zac/app/planitems/converter/RESTPlanItemConverter.java
src/main/java/net/atos/zac/app/planitems/model/RESTPlanItem.java

BUG: Groepcomponent neemt de parameterinstellingen van taken niet over #1780

BUG: Groepcomponent neemt de parameterinstellingen van taken niet over #1780

---

src/main/app/src/app/notities/notities.component.html
src/main/app/src/app/shared/material-form-builder/form-components/select-medewerker/medewerker-groep.component.html

BUG: Id's Zaaktoewijzing / Notitie / Notitie bewerken graag toevoegen #1806

BUG: Id's Zaaktoewijzing / Notitie / Notitie bewerken graag toevoegen #1806

---

src/main/app/src/app/admin/mailtemplates/mailtemplates.component.html
src/main/app/src/app/admin/mailtemplates/mailtemplates.component.ts
src/main/app/src/app/admin/model/mailtemplate-variabele.ts
src/main/app/src/app/admin/model/mailtemplate.ts
src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/mail/ontvangstbevestiging/ontvangstbevestiging.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor-form-field-builder.ts
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor-form-field.ts
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor.component.ts
src/main/java/net/atos/zac/app/admin/converter/RESTMailtemplateConverter.java
src/main/java/net/atos/zac/app/admin/model/RESTMailtemplate.java
src/main/java/net/atos/zac/mail/MailService.java
src/main/java/net/atos/zac/mailtemplates/model/MailTemplateVariabelen.java

zaakafhandelcomponent-1803 - Mailtemplate variabelen review commentaar + enkele bugs

zaakafhandelcomponent-1803 - Mailtemplate variabelen review commentaar + enkele bugs

---

src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekopdracht.component.ts
src/main/app/src/app/shared/table-zoek-filters/date-range-filter/date-range-filter.component.html
src/main/app/src/app/shared/table-zoek-filters/date-range-filter/date-range-filter.component.ts
src/main/app/src/app/zoeken/model/datum-range.ts
src/main/app/src/app/zoeken/zoek/filters/date-filter/date-filter.component.ts
src/main/app/src/app/zoeken/zoek/zoek.component.ts

fix voor inbox en ontkoppelde documenten

zaakafhandelcomponent-1880 tonen van documenten

---

src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java

zaakafhandelcomponent-1874 Hoofdzaak herindexeren bij koppelen

---

src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/documentcreatie/model/TaakData.java
src/main/java/net/atos/zac/mail/MailService.java
src/main/java/net/atos/zac/mailtemplates/model/MailTemplateVariabelen.java

zaakafhandelcomponent-1909 - Verbeteringen/aanvulling mailtemplates deel 1

zaakafhandelcomponent-1909 - Verbeteringen/aanvulling mailtemplates deel 1

---

src/main/java/net/atos/client/zgw/ztc/ZTCClientService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/healthcheck/HealthCheckService.java
src/main/java/net/atos/zac/util/LocalDateUtil.java

zaakafhandelcomponent-1913 Alleen geldige besluittypen tonen

---

src/main/app/src/app/formulieren/taken/model/advies.ts

zaakafhandelcomponent-1939 - Toelichting bij advies taak wordt niet getoond

zaakafhandelcomponent-1939 - Toelichting bij advies taak wordt niet getoond

---

src/main/java/net/atos/zac/solr/schema/SolrSchemaV2.java

ZAC start niet op, moet zaak_einddatumGepland zijn ipv zaak_streefdatum

zaakafhandelcomponent-2013 zaakafhandelcomponent-1438 ACCEPTATIE BUG: Taak heeft geen fatale datum

---

src/main/app/src/app/informatie-objecten/model/gekoppelde.zaak.enkelvoudig.informatieobject.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTGekoppeldeZaakEnkelvoudigInformatieObject.java

zaakafhandelcomponent-1937 - Verwijderen document op gekoppelde zaak

zaakafhandelcomponent-1937 - Verwijderen document op gekoppelde zaak

---

src/main/java/net/atos/zac/app/zoeken/converter/RESTDocumentZoekObjectConverter.java
src/main/java/net/atos/zac/app/zoeken/converter/RESTTaakZoekObjectConverter.java
src/main/java/net/atos/zac/app/zoeken/converter/RESTZaakZoekObjectConverter.java
src/main/java/net/atos/zac/app/zoeken/model/AbstractRESTZoekObject.java

zaakafhandelcomponent-2027 BUG: werkvoorraad taken opent niet

---

src/main/app/src/app/zoeken/zoek-object/zoek-object-link/zoek-object-link.component.html
src/main/app/src/app/zoeken/zoek-object/zoek-object-link/zoek-object-link.component.less

max 3 indicaties  naast elkaar, en new tab icon verwijderen op ctrl

zaakafhandelcomponent-1924 Indicaties tonen in de zoekresultaten

---

src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java
src/main/java/net/atos/client/zgw/zrc/model/Rol.java
src/main/java/net/atos/client/zgw/zrc/model/RolMedewerker.java
src/main/java/net/atos/client/zgw/zrc/model/RolNatuurlijkPersoon.java
src/main/java/net/atos/client/zgw/zrc/model/RolNietNatuurlijkPersoon.java
src/main/java/net/atos/client/zgw/zrc/model/RolOrganisatorischeEenheid.java
src/main/java/net/atos/client/zgw/zrc/model/RolVestiging.java
src/main/java/net/atos/zac/aanvraag/ProductAanvraagService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java

Deel 1/3 prefixen betrokkene type

zaakafhandelcomponent-1895 Deel 1/3 prefixen betrokkene type

---

src/main/app/src/app/admin/mailtemplate/mailtemplate.component.ts

zaakafhandelcomponent-2002 - Signalering mails tonen lege combobox

zaakafhandelcomponent-2002 - Signalering mails tonen lege combobox

---

src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java

zaakafhandelcomponent-2035 - Datum volgorde aanpassing voor mailtemplates

zaakafhandelcomponent-2035 - Datum volgorde aanpassing voor mailtemplates

---

src/main/resources/schemas/V41__mail_template_rename.sql

Fix script

---

src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor-variabelen-kies-menu.component.html
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor-variabelen-kies-menu.component.less
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor-variabelen-kies-menu.component.ts

zaakafhandelcomponent-2001 Geen max-width op variabelen menu

---

src/main/app/src/app/admin/mailtemplate/mailtemplate.component.ts
src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/formulieren/taken/model/extern-advies-mail.ts
src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/mail/ontvangstbevestiging/ontvangstbevestiging.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor.component.html

zaakafhandelcomponent-2059 - Limit op leestekens in mail

zaakafhandelcomponent-2059 - Limit op leestekens in mail

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html

zaakafhandelcomponent-2031 Voeg datum pipe toe voor datum

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html

zaakafhandelcomponent-1918 Verwijder overbodige translate-pipe

---

src/main/java/net/atos/zac/csv/CsvService.java

zaakafhandelcomponent-1585 - CSV export kunnen openen in excel via dubbelklik

zaakafhandelcomponent-1585 - CSV export kunnen openen in excel via dubbelklik

---

src/main/app/src/app/shared/indicaties/informatie-object-indicaties/informatie-object-indicaties.component.ts
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

zaakafhandelcomponent-1919 - Enkelvoudig informatie object update event voor ondertekenen

zaakafhandelcomponent-1919 - Enkelvoudig informatie object update event voor ondertekenen

---

src/main/app/src/app/shared/material-form-builder/form-components/date/date.component.ts
src/main/app/src/app/shared/material-form-builder/model/form-component.ts
src/main/app/src/app/shared/validators/customValidators.ts
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.less
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.ts

Intake is klaar, afhandelen moet nog

zaakafhandelcomponent-2045 BUG: Zaps instelling statusmails wordt niet overgenomen

---

pom.xml
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-2073 - Extra velden meenemen in pdf document voor verzonden mail

zaakafhandelcomponent-2073 - Extra velden meenemen in pdf document voor verzonden mail

---

src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.less
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.ts

zaakafhandelcomponent-2137 Inhoud van statusmails weergeven

zaakafhandelcomponent-2137 Inhoud van statusmails weergeven 

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

zaakafhandelcomponent-2071 KAMPEN: andere indeling van Zaak-actie-buttons

zaakafhandelcomponent-2071 KAMPEN: andere indeling van Zaak-actie-buttons 

---

src/main/app/src/app/formulieren/taken/model/goedkeuren.ts

zaakafhandelcomponent-2070 KAMPEN; placeholder textarea 'toelichting goedkeuren' wijzigen

zaakafhandelcomponent-2070 KAMPEN; placeholder textarea 'toelichting goedkeuren' wijzigen  

---

src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts
src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/formulieren/taken/taak-formulier-builder.ts
src/main/app/src/app/plan-items/model/human-task-data.ts
src/main/app/src/app/shared/material-form-builder/form-components/date/date-form-field-builder.ts
src/main/app/src/app/shared/material-form-builder/form-components/date/date-form-field.ts
src/main/app/src/app/shared/material-form-builder/form-components/date/date.component.html
src/main/app/src/app/shared/material-form-builder/form-components/date/date.component.less
src/main/app/src/app/shared/material-form-builder/form-components/date/date.component.ts
src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts
src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
src/main/java/net/atos/zac/app/planitems/model/RESTHumanTaskData.java
src/main/java/net/atos/zac/flowable/TaakVariabelenService.java

zaakafhandelcomponent-2129 TaakVariabelenService.TAAK_DATA_DOORLOPTIJD omzetten naar Taak.duedate

zaakafhandelcomponent-2129 TaakVariabelenService.TAAK_DATA_DOORLOPTIJD omzetten naar Taak.duedate 

---

src/main/app/src/app/admin/inrichtingscheck/inrichtingscheck.component.html
src/main/app/src/app/admin/inrichtingscheck/inrichtingscheck.component.ts

zaakafhandelcomponent-2102 Implementeer sortering voor inrichtingscheck

---

src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-2157 - Variabelen in pdf worden niet geresolved

zaakafhandelcomponent-2157 - Variabelen in pdf worden niet geresolved

---

src/main/java/net/atos/zac/mail/MailService.java

zaakafhandelcomponent-2185 - Onderwerp en ontvanger omwisselen

zaakafhandelcomponent-2185 - Onderwerp en ontvanger omwisselen

---

src/main/app/src/app/core/service/util.service.ts
src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts

zaakafhandelcomponent-2166 Refactor vertaling en implementeer enum key lookup

---

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

zaakafhandelcomponent-2156 - Fout bij toevoegen taakdocument

zaakafhandelcomponent-2156 - Fout bij toevoegen taakdocument

---

src/main/app/src/app/core/actionbar/action-bar.component.html
src/main/app/src/app/core/actionbar/action-bar.component.less

zaakafhandelcomponent-2268 ActionBar Layout fix

---

src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.ts

zaakafhandelcomponent-2298 Laad medewerkers in groep direct

---

src/main/app/src/app/shared/edit/edit-groep-behandelaar/edit-groep-behandelaar.component.html
src/main/app/src/app/shared/edit/edit-groep-behandelaar/edit-groep-behandelaar.component.ts

zaakafhandelcomponent-2311 Subjectize showAssignToMe

---

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts

zaakafhandelcomponent-2021 Verwijder ng14-workaround

---

src/main/app/src/app/documenten/documenten-routing.module.ts
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/gebruikersvoorkeuren/gebruikersvoorkeuren.service.ts
src/main/app/src/app/shared/dynamic-table/datasource/tabel-gegevens-resolver.service.ts
src/main/app/src/app/shared/dynamic-table/datasource/werklijst-component.ts
src/main/app/src/app/shared/dynamic-table/model/tabel-gegevens.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-routing.module.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
src/main/app/src/app/zaken/zaken-routing.module.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
src/main/java/net/atos/zac/app/gebruikersvoorkeuren/GebruikersvoorkeurenRESTService.java
src/main/java/net/atos/zac/app/gebruikersvoorkeuren/model/RESTTabelGegevens.java
src/main/java/net/atos/zac/gebruikersvoorkeuren/GebruikersvoorkeurenService.java
src/main/java/net/atos/zac/gebruikersvoorkeuren/model/TabelInstellingen.java

zaakafhandelcomponent-2215 OLDENZAAL: Aantal items per pagina instelling vasthouden
front-end

zaakafhandelcomponent-2215 OLDENZAAL: Aantal items per pagina instelling vasthouden

---

src/main/app/src/app/documenten/documenten-routing.module.ts
src/main/app/src/app/shared/dynamic-table/datasource/tabel-gegevens-resolver.service.ts
src/main/app/src/app/taken/taken-routing.module.ts
src/main/app/src/app/zaken/zaken-routing.module.ts

fix werklijsten #2215

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-2170 - Document downloaden vanaf zaakscherm`

zaakafhandelcomponent-2170 - Document downloaden vanaf zaakscherm`

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts
src/main/app/src/app/shared/pipes/bestandsomvang.pipe.ts
src/main/app/src/app/shared/pipes/pipes.module.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-2241 - documentomvang tonen

zaakafhandelcomponent-2241 - documentomvang tonen

---

src/main/app/src/app/shared/status-label/status-label.component.less

zaakafhandelcomponent-2310 - Statusblok wordt afgeknipt

zaakafhandelcomponent-2310 - Statusblok wordt afgeknipt

---

src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.html

zaakafhandelcomponent-2257 Geen mat-select-trigger tonen

---

src/main/app/src/app/klanten/klant-zaken-tabel/klant-zaken-tabel.component.html
src/main/app/src/app/klanten/klant-zaken-tabel/klant-zaken-tabel.component.ts

zaakafhandelcomponent-2212 - Groep + behandelaar bij klant zaken tabel

zaakafhandelcomponent-2212 - Groep + behandelaar bij klant zaken tabel

---

src/main/app/src/app/taken/taak-view/taak-view.component.less

zaakafhandelcomponent-2307 - Maximale breedte taakformulier

zaakafhandelcomponent-2307 - Maximale breedte taakformulier

---

src/main/app/src/app/zoeken/zoek-object/zoek-object-link/zoek-object-link.component.less

zaakafhandelcomponent-2305 - Uitlijnen zoekresultaten

zaakafhandelcomponent-2305 - Uitlijnen zoekresultaten

---

src/main/app/src/app/core/toolbar/toolbar.component.html
src/main/app/src/app/core/toolbar/toolbar.component.less

zaakafhandelcomponent-2276 - Uitlijnen van de 4 iconen op toolbar

zaakafhandelcomponent-2276 - Uitlijnen van de 4 iconen op toolbar

---

src/main/app/src/app/klanten/klant-zaken-tabel/klant-zaken-tabel.component.ts

zaakafhandelcomponent-2308 - Tekstzoekvelden klant gegevens werken niet

zaakafhandelcomponent-2308 - Tekstzoekvelden klant gegevens werken niet

---

src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-2391 - Vertaling bestandsomvang

zaakafhandelcomponent-2391 - Vertaling bestandsomvang

---

src/main/app/src/app/shared/dynamic-table/column-picker/column-picker.component.html
src/main/app/src/app/shared/dynamic-table/column-picker/column-picker.component.ts
src/main/app/src/app/shared/dynamic-table/pipes/sort.pipe.ts
src/main/app/src/app/shared/shared.module.ts

zaakafhandelcomponent-2379 Kolommen zaken alfabetisch sorteren

---

src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts

zaakafhandelcomponent - 2406 - BUG: Afzender wordt niet op de taak getoond

zaakafhandelcomponent - 2406 - BUG: Afzender wordt niet op de taak getoond

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent - 2394 - Gerelateerde documenten van koppelzaak inzien werkt niet meer

zaakafhandelcomponent - 2394 - Gerelateerde documenten van koppelzaak inzien werkt niet meer

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

Workaround voor #2382. Voor verdere probleem m.b.t. SkeletonLoader heb ik #2403 aangemaakt.

zaakafhandelcomponent-2382 Workaround voor bug in skeleton loader

---

src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java

fixen product aanvraag - verkerde constructor

zaakafhandelcomponent-2249 10C3.1.6 Zoeken BAG-objecten

---

src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/shared/table-zoek-filters/date-range-filter/date-range-filter.component.html
src/main/app/src/app/shared/table-zoek-filters/facet-filter/facet-filter.component.html
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/app/src/assets/werklijsten.less

zaakafhandelcomponent-2354 - Layour wijzigingen werklijsten

zaakafhandelcomponent-2354 - Layour wijzigingen werklijsten

---

src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/formulieren/taken/model/advies.ts
src/main/app/src/app/formulieren/taken/model/document-verzenden-post.ts
src/main/app/src/app/formulieren/taken/model/extern-advies-mail.ts
src/main/app/src/app/formulieren/taken/model/goedkeuren.ts
src/main/app/src/app/mail/mail-create/mail-create.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst-field-builder.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst-form-field.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.html

zaakafhandelcomponent-2375 - Configurabel maken openen 2e tab voor documentenlijst

zaakafhandelcomponent-2375 - Configurabel maken openen 2e tab voor documentenlijst

---

src/main/app/src/app/app.component.ts
src/main/app/src/app/identity/identity.service.ts

zaakafhandelcomponent-2367 Update sessionStorage user bij laden app

---

src/main/java/net/atos/client/zgw/zrc/model/zaakobjecten/ZaakobjectProductaanvraag.java
src/main/java/net/atos/zac/aanvraag/InboxProductaanvraagService.java
src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java
src/main/java/net/atos/zac/aanvraag/model/InboxProductaanvraag.java
src/main/java/net/atos/zac/documentcreatie/converter/DataConverter.java
src/main/java/net/atos/zac/documenten/InboxDocumentenService.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/resources/schemas/V50__inbox_productaanvraag.sql

zaakafhandelcomponent-319 6A.7.3 Productaanvraag handmatig afhandelen en omzetten naar zaak

---

src/main/app/src/app/informatie-objecten/model/file-icon.ts
src/main/app/src/app/shared/material-form-builder/form-components/file/drag-and-drop.directive.ts
src/main/app/src/app/shared/material-form-builder/form-components/file/file.component.html
src/main/app/src/app/shared/material-form-builder/form-components/file/file.component.ts
src/main/app/src/app/shared/material-form-builder/material-form-builder.module.ts

zaakafhandelcomponent-2385 - drag and drop functionaliteit

zaakafhandelcomponent-2385 - drag and drop functionaliteit

---

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

zaakafhandelcomponent-2373 - BUG: Verplaatsen document vanuit ontkoppelde documenten lijst

zaakafhandelcomponent-2373 - BUG: Verplaatsen document vanuit ontkoppelde documenten lijst

---

src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/app/src/app/taken/taak-view/taak-view.component.less

zaakafhandelcomponent-2307 - BUG: Verkorte taak springt naar beneden bij lang stuk tekst

zaakafhandelcomponent-2307 - BUG: Verkorte taak springt naar beneden bij lang stuk tekst

---

src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/shared/material-form-builder/form-components/divider/divider.component.html

zaakafhandelcomponent-2355 - BUG: blok opmerkingen bij taak Aanvullende informatie

zaakafhandelcomponent-2355 - BUG: blok opmerkingen bij taak Aanvullende informatie

---

src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.html
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.ts

zaakafhandelcomponent-2443 - Verwijderen filter optie op documentcomponent

zaakafhandelcomponent-2443 - Verwijderen filter optie op documentcomponent

---

src/main/app/src/app/productaanvragen/inbox-productaanvragen-list/inbox-productaanvragen-list.component.html
src/main/app/src/app/productaanvragen/inbox-productaanvragen-list/inbox-productaanvragen-list.component.ts
src/main/app/src/app/productaanvragen/model/inbox-productaanvraag.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java
src/main/java/net/atos/zac/aanvraag/model/InboxProductaanvraag.java
src/main/java/net/atos/zac/app/productaanvragen/converter/RESTInboxProductaanvraagConverter.java
src/main/java/net/atos/zac/app/productaanvragen/model/RESTInboxProductaanvraag.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/resources/schemas/V51__inbox_productaanvraag_aantal_bijlagen.sql

bij starten zaak direct vanuit de productaanvraag

zaakafhandelcomponent-2178 Toegevoegde bijlagen in Open Formulieren

---

src/main/app/src/app/informatie-objecten/informatie-objecten.module.ts
src/main/app/src/app/shared/indicaties/informatie-object-indicaties/informatie-object-indicaties.component.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst-field-builder.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst-form-field.ts
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.html
src/main/app/src/app/shared/material-form-builder/form-components/documenten-lijst/documenten-lijst.component.ts
src/main/app/src/app/shared/material-form-builder/material-form-builder.module.ts
src/main/app/src/app/shared/shared.module.ts
src/main/app/src/app/zaken/zaken.module.ts
src/main/app/src/app/zoeken/zoeken.module.ts

zaakafhandelcomponent-2442 - Indicaties toevoegen op documentlijstcomponent

zaakafhandelcomponent-2442 - Indicaties toevoegen op documentlijstcomponent

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

zaakafhandelcomponent-2332 - Document bewerken in zaakscherm

zaakafhandelcomponent-2332 - Document bewerken in zaakscherm

---

src/main/java/net/atos/zac/aanvraag/InboxProductaanvraagService.java

zaakafhandelcomponent-2469 BUG: Zoeken op datum in productaanvraag werkvoorraad

zaakafhandelcomponent-2469 BUG: Zoeken op datum in productaanvraag werkvoorraad

---

src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts
src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/formulieren/taken/model/advies.ts
src/main/app/src/app/formulieren/taken/model/document-verzenden-post.ts
src/main/app/src/app/formulieren/taken/model/goedkeuren.ts
src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/java/net/atos/zac/app/taken/TakenRESTService.java

zaakafhandelcomponent-2441 - Toelichting in taakgegevens verwijderen

zaakafhandelcomponent-2441 - Toelichting in taakgegevens verwijderen

---

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts

zaakafhandelcomponent-2488 - nullpointer op document bij taak

zaakafhandelcomponent-2488 - nullpointer op document bij taak

---

src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts
src/main/app/src/app/taken/taak-view/taak-view.component.ts

zaakafhandelcomponent-2480 - Bijlagen bij aanvullende informatie taak worden niet getoond

zaakafhandelcomponent-2480 - Bijlagen bij aanvullende informatie taak worden niet getoond

---

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

zaakafhandelcomponent-2479 - Behandelaar mag document niet verzenden

zaakafhandelcomponent-2479 - Behandelaar mag document niet verzenden

---

src/main/app/src/app/shared/directives/outside-click.directive.ts
src/main/app/src/app/taken/model/taak-toekennen-gegevens.ts
src/main/app/src/app/taken/model/taak-verdelen-gegevens.ts
src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.ts
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.html
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.ts
src/main/app/src/app/taken/taken.service.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.ts
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.ts
src/main/java/net/atos/zac/app/taken/model/RESTTaakToekennenGegevens.java
src/main/java/net/atos/zac/app/taken/model/RESTTaakVerdelenGegevens.java

zaakafhandelcomponent-2131 - Bij overdragen taak de reden vastleggen

zaakafhandelcomponent-2131 - Bij overdragen taak de reden vastleggen

---

src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.html
src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts
src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.html
src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts

#2518 Wis alles knop op zoeken persoon/bedrijf

#2518 Wis alles knop op zoeken persoon/bedrijf

---

src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-verplaats.service.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

zaakafhandelcomponent-2557 BUG: inboxdocumenten kunnen niet geplakt worden in de zaak

zaakafhandelcomponent-2557 BUG: inboxdocumenten kunnen niet geplakt worden in de zaak
